export const PROVIDERS = [
  { name: 'DeepSeek', slug: 'deepseek', color: '#4D6BFE', tag: '国产' },
  { name: '阿里通义千问', slug: 'qwen', color: '#615CED', tag: '国产' },
  { name: '百度文心一言', slug: 'wenxin', color: '#2932E1', tag: '国产' },
  { name: '智谱 ChatGLM', slug: 'chatglm', color: '#3859FF', tag: '国产' },
  { name: '字节豆包', slug: 'doubao', color: '#3F66FF', tag: '国产' },
  { name: '腾讯混元', slug: 'hunyuan', color: '#007BFF', tag: '国产' },
  { name: '讯飞星火', slug: 'spark', color: '#1E88E5', tag: '国产' },
  { name: '月之暗面 Moonshot', slug: 'moonshot', color: '#1E1E1E', tag: '国产' },
  { name: '百川智能', slug: 'baichuan', color: '#FF6B35', tag: '国产' },
  { name: '阶跃星辰', slug: 'stepfun', color: '#7B61FF', tag: '国产' },
  { name: '零一万物', slug: 'zeroone', color: '#1B4DB1', tag: '国产' },
  { name: '商汤日日新', slug: 'minimax', color: '#FF6B00', tag: '国产' },
  { name: 'InternLM', slug: 'internlm', color: '#1E64C8', tag: '国产' },
  { name: '硅基流动', slug: 'siliconcloud', color: '#7E3FF2', tag: '国产' },
  { name: 'AIHubMix 推理时代', slug: 'aihubmix', color: '#FF7E36', tag: '国产' },
  { name: 'OpenAI', slug: 'openai', color: '#10A37F', tag: '海外' },
  { name: 'Anthropic Claude', slug: 'claude', color: '#D97757', tag: '海外' },
  { name: 'Google Gemini', slug: 'gemini', color: '#4285F4', tag: '海外' },
  { name: 'Mistral AI', slug: 'mistral', color: '#FA520F', tag: '海外' },
  { name: 'Meta LLaMA', slug: 'palm', color: '#0467DF', tag: '海外' },
  { name: 'Google Gemma', slug: 'gemma', color: '#4285F4', tag: '海外' },
  { name: 'xAI Grok', slug: 'grok', color: '#1E1E1E', tag: '海外' },
  { name: 'Cohere', slug: 'cohere', color: '#39594D', tag: '海外' },
  { name: 'Groq', slug: 'groq', color: '#F55036', tag: '海外' },
  { name: 'Ollama', slug: 'ollama', color: '#1A1A1A', tag: '海外' },
  { name: 'OpenRouter', slug: 'openrouter', color: '#5C6BC0', tag: '海外' },
  { name: 'Together AI', slug: 'together', color: '#0E0E0E', tag: '海外' },
  { name: 'Novita AI', slug: 'novita', color: '#FF4D4F', tag: '海外' },
  { name: 'Cloudflare', slug: 'cloudflare', color: '#F38020', tag: '海外' },
  { name: 'AI21 Labs', slug: 'ai21', color: '#003D5B', tag: '海外' },
  { name: 'Stability AI', slug: 'stability', color: '#7B2CBF', tag: '海外' },
  { name: 'Midjourney', slug: 'midjourney', color: '#1B1B1B', tag: '海外' },
  { name: 'DALL·E', slug: 'dalle', color: '#10A37F', tag: '海外' },
  { name: 'Replicate', slug: 'replicate', color: '#000000', tag: '海外' },
  { name: 'Runway', slug: 'runway', color: '#1A1A1A', tag: '海外' },
  { name: 'Suno', slug: 'suno', color: '#FF5500', tag: '海外' },
  { name: 'Perplexity', slug: 'perplexity', color: '#1FB8CD', tag: '海外' },
  { name: 'Phind', slug: 'phind', color: '#17B8A6', tag: '海外' },
  { name: 'Devin', slug: 'devin', color: '#4040FF', tag: '海外' },
  { name: 'Hugging Face', slug: 'huggingface', color: '#FFD21E', tag: '海外' },
]

export const CHANNEL_TYPE_MAP = {
  openai: 1,
  claude: 2,
  azure: 3,
  gemini: 4,
  baidu: 5,
  aliyun: 6,
  tencent: 7,
  xunfei: 8,
  zhipu: 9,
  deepseek: 10,
  midjourney: 11,
}

export function findProviderByName(name) {
  if (!name) return null
  const lower = String(name).toLowerCase()
  return PROVIDERS.find((p) => p.slug === lower || p.name.toLowerCase().includes(lower))
}
